language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: hiPUcKKkw/hJhGNnyQP/apX5OVXKxoBRNxigdphBhmynrJDtY2UFewEPMzY2EizpxlH32QWRE7koT4AZqynRN7YaUPoBREMQ4TCAX60mdz6R+9OguG3K13fong3n1oqM6lIrRGmiQ3nWGOdxZ3YCmJD+p12ekDre8tK/fY4V7G8=
  on:
    all_branches: true
    tags: true
    repo: bealearts/polyglot
