language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: W5yZVfirjkfWQqMYCAJG5SCppPtnXPo0eWHNl0P8LLLNxDd9FlBbkFvNESd270zBM9E1vtF590mpNYy29VAJmgu4PrbNDmSHMfcvTVoufOTpM7Nycy+UejXzDiJqsE/0XX3VcOgTA5h1DVAql76OXv10EJ3oiPFNpn5THItjOao=
  on:
    all_branches: true
    tags: true
    repo: bealearts/polyglot
