language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: F6WJmOsCBoYz24tiktCH1zQ9hh3aDtGytgAYZhyMVg57JsryheE+oJiJka39mefYJYqGJRvdGNDXcBxgEfAjg1RM+tMn3O8YfPMI1LeZo7RzQjf4en/tB1thAbES6L1kcoMDCEw4YWRwuMBCkuCNP/CRaDK9r5SpbJHOje0BKpE=
  on:
    all_branches: true
    tags: true
    repo: bealearts/polyshell
